# usually will be gitignored to not have it commited to GitHub
# example .toml file to connect app to specified database
[connections.my_database]
    type="sql"
    dialect="mysql"
    username="xxx"
    password="xxx"
    host="example.com" # IP or URL
    port=3306 # Port number
    database="mydb" # Database name
